export async function GET() {
  try {
    const plans = [
      {
        id: 'free',
        name: 'Free',
        nameAr: 'مجاني',
        price: 0,
        priceAr: 'مجاني',
        interval: 'monthly',
        features: [
          'Browse products & stores',
          'Basic search',
          'Up to 5 wishlist items',
          'Standard customer support',
          'Order tracking',
        ],
        featuresAr: [
          'تصفح المنتجات والمتاجر',
          'بحث أساسي',
          'حتى 5 عناصر في قائمة الرغبات',
          'دعم عملاء قياسي',
          'تتبع الطلبات',
        ],
        limits: {
          maxWishlistItems: 5,
          maxOrdersPerMonth: null,
          aiCredits: 0,
          freeShipping: false,
          exclusiveDeals: false,
          prioritySupport: false,
          earlyAccess: false,
        },
        popular: false,
        cta: 'Current Plan',
        ctaAr: 'الخطة الحالية',
      },
      {
        id: 'pro',
        name: 'Pro',
        nameAr: 'احترافي',
        price: 9.99,
        priceAr: '٩.٩٩',
        interval: 'monthly',
        features: [
          'Everything in Free',
          'Unlimited wishlist',
          'AI-powered recommendations',
          '10 AI credits per month',
          'Free shipping on orders $50+',
          'Exclusive deals access',
          'Priority customer support',
          'Price drop alerts',
        ],
        featuresAr: [
          'كل شيء في المجاني',
          'قائمة رغبات غير محدودة',
          'توصيات مدعومة بالذكاء الاصطناعي',
          '١٠ أرصدة ذكاء اصطناعي شهرياً',
          'شحن مجاني للطلبات فوق ٥٠$',
          'وصول للعروض الحصرية',
          'دعم عملاء ذو أولوية',
          'تنبيهات انخفاض الأسعار',
        ],
        limits: {
          maxWishlistItems: null,
          maxOrdersPerMonth: null,
          aiCredits: 10,
          freeShipping: true,
          freeShippingThreshold: 50,
          exclusiveDeals: true,
          prioritySupport: true,
          earlyAccess: false,
        },
        popular: true,
        cta: 'Upgrade to Pro',
        ctaAr: 'الترقية إلى الاحترافي',
      },
      {
        id: 'premium',
        name: 'Premium',
        nameAr: 'متميز',
        price: 24.99,
        priceAr: '٢٤.٩٩',
        interval: 'monthly',
        features: [
          'Everything in Pro',
          '50 AI credits per month',
          'Free shipping on all orders',
          'Early access to new products',
          'VIP customer support',
          'Exclusive premium deals',
          'Visual search unlimited',
          'Smart pricing insights',
          'Personal shopping assistant',
          'Birthday rewards',
        ],
        featuresAr: [
          'كل شيء في الاحترافي',
          '٥٠ رصيد ذكاء اصطناعي شهرياً',
          'شحن مجاني على جميع الطلبات',
          'وصول مبكر للمنتجات الجديدة',
          'دعم عملاء VIP',
          'عروض متميزة حصرية',
          'بحث بصري غير محدود',
          'رؤى تسعير ذكية',
          'مساعد تسوق شخصي',
          'مكافآت عيد الميلاد',
        ],
        limits: {
          maxWishlistItems: null,
          maxOrdersPerMonth: null,
          aiCredits: 50,
          freeShipping: true,
          freeShippingThreshold: 0,
          exclusiveDeals: true,
          prioritySupport: true,
          earlyAccess: true,
        },
        popular: false,
        cta: 'Upgrade to Premium',
        ctaAr: 'الترقية إلى المتميز',
      },
    ];

    return Response.json({ plans });
  } catch (error) {
    console.error('Subscriptions API error:', error);
    return Response.json({ error: 'Failed to fetch subscription plans' }, { status: 500 });
  }
}
